name: Release to CloudFlare Prod

on:
  push:
    branches:
      - prod

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:

  deploy_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci && npm run docs:build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'docs-deploy-my' # e.g. 'my-project'
          directory: '.vitepress/dist' # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}