name: Release to CloudFlare Prod

on:
  push:
    branches:
      - prod

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:

  deploy_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to DeployStack.io
    environment:
      name: 'Production'
      url: https://deploystack.io/docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "Executing webhook to deploy"